# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorespond', '0018_autoresponse_admin_override_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresponse',
            name='admin_override_email',
            field=models.TextField(blank=True, help_text='A different user-provided email to receive notifications.'),
        ),
        migrations.AlterField(
            model_name='autoresponse',
            name='credentials',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autorespond.GoogleCredential', verbose_name='autorespond account'),
        ),
        migrations.AlterField(
            model_name='autoresponse',
            name='disable_responses',
            field=models.BooleanField(default=False, help_text='Enable to never autorespond (overriding other settings). Email notifications may still be sent.'),
        ),
        migrations.AlterField(
            model_name='autoresponse',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Enable to receive an email when an autoresponse is sent.'),
        ),
        migrations.AlterField(
            model_name='autoresponse',
            name='status_detection',
            field=models.BooleanField(default=True, help_text='Disable to autorespond even when active in gmail or a mobile device.'),
        ),
        migrations.AlterField(
            model_name='autoresponse',
            name='throttle_mins',
            field=models.PositiveSmallIntegerField(default=5, help_text='After autoresponding, wait this many minutes before responding again to the same contact. Setting to 0 will respond to every message.', verbose_name='rate limit (minutes)'),
        ),
        migrations.AlterField(
            model_name='excludeduser',
            name='autorespond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorespond.AutoResponse', verbose_name='autorespond'),
        ),
        migrations.AlterField(
            model_name='excludeduser',
            name='email_notifications',
            field=models.CharField(choices=[('DE', 'default'), ('AL', 'always'), ('NE', 'never')], default='DE', help_text="Use 'always' or 'never' to override the email notification setting for this user.", max_length=2),
        ),
        migrations.AlterField(
            model_name='excludeduser',
            name='name',
            field=models.CharField(help_text="A contact's full name as it appears when you chat with them. Capitalization is ignored.", max_length=128),
        ),
        migrations.AlterField(
            model_name='lastresponse',
            name='autorespond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorespond.AutoResponse', verbose_name='autorespond'),
        ),
    ]
