# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 09:57
from __future__ import unicode_literals

from django.db import migrations
import gchatautorespond.apps.autorespond.models


class Migration(migrations.Migration):

    dependencies = [
        ('autorespond', '0019_auto_20190721_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecredential',
            name='credentials',
            field=gchatautorespond.apps.autorespond.models.CompatCredentialsField(null=True),
        ),
    ]
