# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_license_notified_trial_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='admin_override',
            field=models.CharField(blank=True, choices=[('EN', 'Enable'), ('DI', 'Disable')], max_length=2),
        ),
    ]
