---

- hosts: appservers
  remote_user: "{{ appuser }}"
  vars_files:
      - secrets.yml
  tasks:
    - name: shut down an existing djsupervisor
      command: "{{ venv }}/exec python manage.py supervisor shutdown"
      args:
          chdir: "{{ appdir }}"
          ignore_errors: yes

    - name: restore database
      sudo: true
      command: "duply gchat_db3 restore --force"
      register: duply_result

    - debug: var=duply_result

    - name: start djsupervisor
      command: "{{ venv }}/exec python manage.py supervisor --daemonize"
      args:
          chdir: "{{ appdir }}"
